# Generated by Django 3.2.7 on 2021-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('State', models.IntegerField(choices=[(1, 'draft'), (2, 'active'), (3, 'done'), (4, 'archived')])),
            ],
        ),
    ]
